# GLOBAL SITE SETTINGS

# General
seo_title: "VACSWIM South Australia - Swimming and Water Safety, Water Survival for Children"
title: "VACSWIM South Australia"
company: "VACSWIM"
logo: "/img/content/logo.png"
affiliate_logo: "/img/content/ymca-logo.png"
affiliate_link: "http://www.sa.ymca.org.au/"
description: "The VACSWIM program is a South Australian government funded program for children aged 5 - 13 years. The program provides participants with opportunities to develop a range of skills and positive experiences in the areas of water safety, confidence/competence in the water, personal survival activities, emergency procedures and basic swimming stroke improvement."

# Contact Info
email: vacswimsa@ymca.org.au
phone: (08) 8200 2525
fax: (08) 8353 0384
office_address: "46 Cowan St, Angle Park SA 5010"
postal_address: "PO Box 20, Fulham Gardens SA 5024"
office_hours: "Monday to Friday, 9amÂ to 5pm"

# Social Networks
facebook: "https://www.facebook.com/vacswimsa"

# Google Map
google_map: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3273.9024253121343!2d138.556808!3d-34.85867899999999!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x6ab0c7d5d7491855%3A0x1f39f313804cfc3e!2sThe+Parks+Recreation+and+Sports+Centre!5e0!3m2!1sen!2sus!4v1410828227925"